[workspace]
resolver = "3"
members = [
    "crates/qexed",
    "crates/qexed_log",
    "crates/qexed_config",
    "crates/qexed_config_autodoc",
    "crates/qexed_entity",
    "crates/qexed_player",
    "crates/qexed_plugin_api",
    "crates/macros/qexed_config_macros",
    "crates/macros/qexed_packet_macros",
    "crates/qexed_tcp_connect",
    "crates/qexed_packet",
    "crates/qexed_protocol",
    "crates/qexed_nbt", 
    "crates/qexed_tools",
    "crates/macros/qexed_error_macros",
]
[workspace.dependencies]
qexed_config = { path = "crates/qexed_config" }
qexed_config_autodoc = { path = "crates/qexed_config_autodoc" }
qexed_entity = { path = "crates/qexed_entity" }
qexed_player = { path = "crates/qexed_player" }
qexed_plugin_api = { path = "crates/qexed_plugin_api" }
qexed_log = { path = "crates/qexed_log" }

qexed_config_macros = {path = "crates/macros/qexed_config_macros"}
qexed_packet_macros.path = "crates/macros/qexed_packet_macros"
qexed_packet.path = "crates/qexed_packet"
qexed_tcp_connect.path = "crates/qexed_tcp_connect"
qexed_protocol.path = "crates/qexed_protocol"
qexed_nbt.path = "crates/qexed_nbt"
qexed_error_macros.path="crates/macros/qexed_error_macros"
# 外部包
# 插件
# pass
# 外部包
thiserror = "1.0"
anyhow = "1.0"                                         # 用于简化错误处理
byteorder = "1.5.0"
tokio = { version = "1.48.0", features = ["full","net"] }
tklog = "0.3.0"
log = "0.4.27"
chrono = "0.4.41"
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.9.5"
once_cell = "1.21.3"
futures = "0.3.31"
tracing = "0.1.41"
typename = "0.1.2"
rand = "0.8.5"
async-stream = "0.3.6"
bytes = "1.11.1"
flate2 = "1.1.2"
serde_json = "1.0.142"
postcard = { version = "1.1.3", features = ["alloc"] }
uuid = { version = "1.17.0", features = ["v3", "v4","serde"] }
reqwest = { version = "0.12.22", features = ["json", "blocking"] }
fmt = "0.1.0"
aes = "0.8.4"
cfb8 = { version = "0.8.1", features = ["aes"] }
cfb-mode = "0.8.2"
mongodb = "3.4.1"
bson = "2.15.0"
simdnoise = "3.1.6"
async-trait = "0.1.88"
tokio-stream = "0.1.17"
phf = "0.12.1"
flume = "0.11.1"
paste = "1.0.15"
ctor = "0.4.3"
ctr = "0.9.2"
futures-util = "0.3.31"
rayon = "1.11.0"
fastrand = "2.3.0"
bitflags = "2.9.3"
moka = { version = "0.12.10", features = ["sync"] }
lazy_static = "1.5.0"
dyn-clone = "1.0.20"
tempfile = "3.23.0"
midly = "0.5.3"
cached = "0.42"
rsa = "0.9"
dashmap = "6.1.0"
wasmtime = "41.0.4"
schemars = { version = "1" }
tokio-util = "0.7.17"
humantime-serde = "1.1.1"
hex = "0.4.3"
sha1 = "0.10.6"
tinytemplate = "1.2.1"
kanal = "0.1.1"
base64 = "0.22.1"
redis = {version = "1.0.2",features = ["tokio-comp", "r2d2", "tls-rustls"]}
mysql_async = "0.36.1"
shadow-rs = "1.5.0"
bb8 = "0.9.1"
bb8-redis = "0.26.0"
bit-vec = "0.8.0"
console-subscriber = "0.5.0"
difference = "2.0"
fs-err = "3.2.2"
haproxy-protocol = "0.0.3"
heck = "0.4"
hmac = "0.12.1"
mockito = "1.7.1"
nanoid = "0.4.0"
openssl = {version ="0.10.80",features = ["vendored"]}
phf_codegen = "0.11"
proc-macro2 = "1.0"
quote = "1.0"
sha2 = "0.10.9"
shlex = "1.3.0"
strum = "0.27.2"
syn = "2.0"
tokio-test = "0.4.4"
vergen = "8"
colored = "3.1.1"
nix = {version = "0.31.1",features = ["user", "poll"]}
regex = "1.12.2"
whoami = "2.1.0"
sys-locale = "0.3.2"
icu = "2.1.1"
rust-i18n = "3.1.5"
sled = "0.34.7"
os_info = "3.14.0"
winapi = "0.3.9"
zip = { version = "2.4.2", default-features = false, features = ["deflate"] }
cargo_toml = "0.22.3"
libloading = "0.9.0"
semver = "1.0.27"
tinykv = "0.4.0"
clap = { version = "4.6.0",features = ["derive"] }
time = "0.3.47"
winres = "0.1"
