[workspace]
resolver = "3"
members = [
    "crates/qexed",
    "crates/qexed_club",
    # 配置核心
    "crates/qexed_config",
    "crates/qexed_toml",
    
    
    # Log
    "crates/qexed_log",

    # 多语言
    "crates/qexed_language",
    "crates/qexed_language_server",
    # 文档
    "crates/qexed_doc",
    "crates/macros/qexed_doc_macros",
    "crates/macros/qexed_config_macros",
    "crates/qexed_doc_to_mdx",

    # 文档示例校验（docker 复现 MDX verify 清单）
    "crates/qexed_doc_verify",

    # Mojang jar数据
    "crates/qexed_mojang_data",
]
[workspace.dependencies]
qexed_toml.path = "crates/qexed_toml"
qexed_config.path = "crates/qexed_config"
qexed_log.path = "crates/qexed_log"
qexed_language.path = "crates/qexed_language"
qexed_doc.path = "crates/qexed_doc"
qexed_doc_macros.path = "crates/macros/qexed_doc_macros"
qexed_config_macros.path = "crates/macros/qexed_config_macros"
qexed_club = { path = 'crates/qexed_club' }
qexed_mojang_data.path = "crates/qexed_mojang_data"

serde = "1.0.229"
serde_json = "1"
clap = { version = "4", features = ["derive"] }
thiserror = "2.0.20"
tokio = "1.53.1"
toml_edit = "0.25.13"
proc-macro2 = "1.0"
quote = "1.0"
syn = "2.0"

shadow-rs = "2.0.0"
chrono = "0.4.45"
colored = "3.1.1"
tklog = "0.3.0"
anyhow = "1.0.104"
log = "0.4.34"
