[package]
name = "qexed"
version = "0.1.0"
edition = "2024"
build = "build.rs"
[dependencies]
qexed_log.workspace = true
qexed_config.workspace = true
qexed_tcp_connect.workspace = true
qexed_packet_macros.workspace = true
qexed_packet.workspace = true
qexed_protocol.workspace = true
log = { workspace = true }
tokio = { workspace = true }
anyhow.workspace = true
rust-i18n = { workspace = true }
shadow-rs.workspace = true
os_info = { workspace = true }
clap.workspace = true
tokio-stream.workspace = true
[build-dependencies]
shadow-rs.workspace = true
