[package]
name = "qexed"
version = "0.1.0"
edition = "2024"

[dependencies]
qexed_log.workspace = true
qexed_config.workspace = true
qexed_update_check.workspace = true
qexed_safe_check.workspace = true
qexed_plugin_manage.workspace = true
qexed_warden.workspace = true
log = { workspace = true }
tklog = { workspace = true }
tokio = { workspace = true }
anyhow.workspace = true
rust-i18n = { workspace = true }
