[package]
name = "qexed_statistics"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
qexed_packet.workspace = true
qexed_protocol.workspace = true
qexed_nbt.workspace = true
qexed_config.workspace = true
qexed_log.workspace = true
qexed_language.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
uuid.workspace = true
log.workspace = true
thiserror.workspace = true

[dev-dependencies]
