[package]
name = "qexed_log"
version = "0.1.0"
edition = "2024"
[package.metadata.log_defaults]
level = "Debug"
console = true
formatter = "{level} [{time}]: [{module}] {file} {message}\n"
file_path = "./logs/{}.log"
file_mode = "DAY"
keep_days = 7
max_size = 10
append = true
[package.metadata.log_modules]
qexed_tcp_connect.rename = "qexed_log.modern.qexed_tcp_connect"
qexed_log.rename = "qexed_log.modern.log"
qexed_update_check.rename ="qexed_log.modern.qexed_update_check"
qexed.rename = "qexed_log.modern.qexed"
qexed_plugin_manage.rename = "qexed_log.modern.qexed_plugin_manage"
qexed_ip_connection_speed_test.rename = "qexed_log.modern.qexed_ip_connection_speed_test"
qexed_wasm_runtime.rename = "qexed_log.modern.qexed_wasm_runtime"
qexed_players.rename = "qexed_log.modern.qexed_players"
qexed_packet_split.rename = "qexed_log.modern.qexed_packet_split"
[dependencies]
colored.workspace = true
chrono.workspace = true
tklog.workspace = true
rust-i18n.workspace = true
[build-dependencies]
chrono.workspace = true
toml.workspace = true
