[package]
name = "qexed_worldgen"
version = "0.1.0"
edition = "2024"

[dependencies]
qexed_config.workspace = true
qexed_nbt.workspace = true
qexed_registry.workspace = true

anyhow.workspace = true
log.workspace = true
openssl.workspace = true
serde.workspace = true
serde_json.workspace = true
rayon.workspace = true

[dev-dependencies]
flate2.workspace = true
tempfile.workspace = true
