[package]
name = "qexed_server_legacy"
version = "0.1.0"
edition = "2024"
description = "Minecraft server connection layer: async packet framing, login, configuration, minimal play. Keeps the qexed binary lean."
license = "MIT"
repository = "https://github.com/qexed/Qexed"

[dependencies]
qexed_packet.workspace = true
qexed_protocol.workspace = true
bytes.workspace = true
flate2.workspace = true
thiserror.workspace = true
tokio.workspace = true
serde_json.workspace = true
uuid = { workspace = true, features = ["v3"] }
qexed_nbt.workspace = true

openssl = { workspace = true }

reqwest = { workspace = true, features = ["json", "rustls-tls"] }

sha1 = { workspace = true }

hex = { workspace = true }

base64 = { workspace = true }

rand = { workspace = true }

serde.workspace = true

anyhow.workspace = true

qexed_mojang_data.workspace = true

log.workspace = true

[dev-dependencies]
uuid = { workspace = true, features = ["v4"] }
qexed_mojang_data.workspace = true
