[package]
name = "qexed_chat"
version = "0.1.0"
edition = "2024"

[dependencies]
qexed_config = { workspace = true, features = ["global-root"] }
qexed_config_macros.workspace = true
qexed_language.workspace = true
qexed_doc.workspace = true
qexed_doc_macros.workspace = true

tokio.workspace = true
tklog.workspace = true
thiserror.workspace = true
serde.workspace = true
qexed_protocol.workspace = true
openssl = { workspace = true }
uuid = { workspace = true }
qexed_packet.workspace = true
