plugins {
    id 'java'
    id 'application'
    id("org.spongepowered.gradle.vanilla") version "0.3.2"
}

group = 'cn.qexed'
version = '1.0-SNAPSHOT'

minecraft {
    version("26.3")
}

application {
    mainClass = 'cn.qexed.Main'
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}