name: Build Rust Project - qexed

on:
  push:
    branches: [main, v6]
  pull_request:
    branches: [main, v6]

permissions:
  contents: read

jobs:
  build-release:
    name: Build release binary for qexed
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: "1.98.1"

      - name: Cache cargo registry and target directory
        uses: Swatinem/rust-cache@v2

      - name: Build release binary
        run: cargo build --release --package qexed --bin qexed
